### ISSUE TITLE
Missing attributes and more

### ISSUE THREAD

**Issue by AndersHoglund** [niklasmelin/nibepi-homeassistant#1]
Hi, 
Am I doing something wrong? I see two problems with NibePi MQTT in HA:

1. NibePi does not turn up as a MQTT device, only a bunch of "sensor.nibe_...." entities. I have other MQTT devices that do appear as devices.
2. Missing attributes on entities to be fully accepted in HA, mainly in energy dashboard and in history. But a general problem. I have added a workaround in my configuration.yaml:
```
homeassistant:
  customize:
    sensor.nibe_airflow_ref:
      unit_of_measurement: "m3/h"
    sensor.nibe_eb100_adjusted_bs1_air_flow:
      unit_of_measurement: "m3/h"
    sensor.nibe_eb100_bs1_air_flow:
      unit_of_measurement: "m3/h"
    sensor.nibe_eb100_bs1_air_flow_unfiltered:
      unit_of_measurement: "m3/h"
    sensor.nibe_hp_consumed_energy_due_to_heating:
      state_class: total_increasing
      device_class: energy
    sensor.nibe_hp_consumed_energy_due_to_hot_water:
      state_class: total_increasing
      device_class: energy
    sensor.nibe_hp_consumed_energy_due_to_ventilation:
      state_class: total_increasing
      device_class: energy
    sensor.nibe_degree_minutes_16_bit:
      unit_of_measurement: ""
    sensor.nibe_degree_minutes_32_bit:
      unit_of_measurement: ""
    sensor.nibe_eb100_be1_current:
        device_class: current
    sensor.nibe_eb100_be2_current:
        device_class: current
    sensor.nibe_eb100_be3_current:
        device_class: current
```

None of those two issues are covered on this otherwise excellent repo. Maybe some info on these issues should be added?. Thank you for a good job.
/A
